apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.apps.tooljet.secret.name }}"
type: Opaque
data:
  {{- if .Values.postgresql.enabled -}}
  PG_HOST: {{ print .Release.Name  "-postgresql" | b64enc | quote }}
  PG_PASS: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  PG_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{- else }}
  PG_HOST: {{ .Values.postgresql.postgresqlHost | b64enc | quote }}
  PG_PORT: {{ .Values.postgresql.postgresqlPort | b64enc | quote }}
  PG_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{- end}}
  PG_DB: {{  .Values.postgresql.auth.database | b64enc | quote }}
  LOCKBOX_MASTER_KEY: {{ .Values.apps.tooljet.secret.data.lockbox_key | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.apps.tooljet.secret.data.secret_key_base | b64enc | quote }}
