blank_issues_enabled: false
contact_links:
  - name: â“ Get Support from Slack Community
    url: https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg
    about: Please ask and answer questions here. ğŸ¥