[build]
  base = "docs/"
  publish = "build"
  command = "git submodule deinit -f --all && GTM=$GTM ALGOLIA_API_KEY=$ALGOLIA_API_KEY npm run build"

[template.environment]
  NODE_ENV = "production"  
  NODE_VERSION = "18.18.2"
  NPM_VERSION = "9.8.1"