[build]
  base = "docs/"
  publish = "build"
  command = "GTM=$GTM ALGOLIA_API_KEY=$ALGOLIA_API_KEY npm run build"
  
  [template.environment]
  NODE_ENV = "production"  
  NODE_VERSION = "16.18.1"
  NPM_VERSION = "8.19.2"
